name1=input("你的名字：")
age1=int(input("你的年龄："))
print("Hello world",f"My name is {name1}",f"My age is {age1}",sep="! ",end="!\n")
name2=input("你的名字：")
age2=int(input("你的年龄："))
print("Hello world","我的名字是:%s"%name2,"我的年龄是:%d"%age2,sep="! ",end="!\n")